language: c
sudo: false

addons:
  apt:
    packages:
    - aspcud
    - libglpk-dev

before_install:
    - bash -exu .travis-ci.sh prepare
install:
    - bash -exu .travis-ci.sh install

cache:
    directories:
    - $HOME/.opam.cached
    - $HOME/local

script:
    - bash -exu .travis-ci.sh build

matrix:
  include:
    - os: linux
      env: OCAML_VERSION=4.07.1
      stage: Build
    - os: windows
      env: COLD=1 CYG_MIRROR=http://mirrors.kernel.org/sourceware/cygwin/
      stage: Test
notifications:
  email:
    - opam-commits@lists.ocaml.org
  irc:
    - "chat.freenode.net#opam"
