dist: xenial
language: c
sudo: false

addons:
  apt:
    packages:
    - aspcud
    - libglpk-dev

before_install:
    - bash -exu .travis-ci.sh prepare
install:
    - bash -exu .travis-ci.sh install

cache:
    directories:
    - $HOME/.opam.2.0.cached
    - $HOME/local
    - $HOME/opam1.2/cache

script:
    - bash -exu .travis-ci.sh build

matrix:
  include:
    - os: linux
      env: OCAML_VERSION=4.09.1 OPAM_TEST=1
      stage: Test

notifications:
  email:
    - opam-commits@lists.ocaml.org
  irc:
    - "chat.freenode.net#opam"
