# NB If minimum OCaml version for Dune changes, update DUNE_SECONDARY in configure.ac
URL_dune-local = https://github.com/ocaml/dune/releases/download/3.17.1/dune-3.17.1.tbz
MD5_dune-local = 11bc43f614d758d28b75e085c86cdcb5
